# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0002_auto_20171005_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('short_bio', models.TextField(max_length=420, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to=b'grumblr/images/profile_picture')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.UserProfile'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
