# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0004_auto_20171006_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
