# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_auto_20171006_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserInfo',
        ),
    ]
